import { db } from './connection.js';

export const INITIAL_CAREER_CATALOG = [
  // 1. TECHNOLOGY & DATA
  {
    id: 'car_data_analyst',
    career_name: 'Data Analyst',
    category: 'Technology & Data',
    description: 'Transform raw datasets into actionable business insights using SQL, spreadsheets, data visualization, and statistical storytelling.',
    interest_areas: ['Technology', 'Computers', 'Business', 'Research', 'Mathematics'],
    work_styles: ['analytical', 'computer_based', 'structured', 'indoor', 'independent'],
    common_skills: ['SQL', 'Spreadsheets & Excel', 'Power BI / Tableau', 'Data Cleaning', 'Basic Python / R', 'Business Metrics'],
    transferable_skills: ['Analytical thinking', 'Problem solving', 'Attention to detail', 'Reporting', 'Pattern recognition'],
    education_pathways: ['Undergraduate Degree (Any quantitative or business field)', 'Certification in Data Analytics', 'Self-taught portfolio with verified datasets'],
    entry_pathways: ['Junior Data Analyst', 'BI Reporting Specialist', 'Operations Analyst', 'Marketing Data Coordinator'],
    learning_areas: ['Relational database querying (SQL)', 'Exploratory data analysis', 'Executive dashboard design', 'A/B testing basics'],
    practical_tasks: ['Write a 4-table SQL query with window functions', 'Clean a dirty CSV dataset and calculate churn rate', 'Build an interactive dashboard on Looker Studio'],
    portfolio_needs: ['3 end-to-end data analysis case studies with problem, query scripts, and interactive visual insights on GitHub'],
    work_environment: ['Tech firms', 'Finance corporations', 'Healthcare institutions', 'Consulting agencies', 'Remote / Hybrid'],
    hands_on_level: 'Low',
    computer_use_level: 'High',
    people_interaction_level: 'Moderate',
    income_potential: 'High',
    learning_duration: '4-6 Months',
    related_careers: ['Business Analyst', 'Data Engineer', 'Marketing Analyst', 'Financial Analyst']
  },
  {
    id: 'car_software_developer',
    career_name: 'Software Developer',
    category: 'Technology & Data',
    description: 'Design, write, and maintain clean software applications, web platforms, and backend services to solve real user problems.',
    interest_areas: ['Technology', 'Computers', 'Engineering', 'Problem Solving'],
    work_styles: ['analytical', 'computer_based', 'creative', 'indoor', 'balanced'],
    common_skills: ['Programming (JavaScript/Python/Java/Go)', 'RESTful APIs', 'Database Architecture', 'Git Version Control', 'Testing & Debugging'],
    transferable_skills: ['Algorithmic logic', 'Systematic debugging', 'Continuous learning', 'Technical documentation'],
    education_pathways: ['B.Tech / B.E. / BCA / B.Sc Computer Science', 'Coding bootcamps', 'Practical open-source project portfolio'],
    entry_pathways: ['Associate Software Engineer', 'Full-Stack Web Developer', 'Backend Intern', 'Junior Frontend Developer'],
    learning_areas: ['Data structures & algorithms', 'Web architectures & HTTP', 'Relational & NoSQL persistence', 'Clean code & unit testing'],
    practical_tasks: ['Build a RESTful CRUD API with authentication', 'Create an interactive web UI with real-time state', 'Containerize a service using Docker'],
    portfolio_needs: ['2-3 deployed web or backend applications with clean GitHub repositories and detailed README architectural diagrams'],
    work_environment: ['SaaS startups', 'Enterprise IT companies', 'Digital product studios', 'Remote / Global'],
    hands_on_level: 'Low',
    computer_use_level: 'High',
    people_interaction_level: 'Moderate',
    income_potential: 'High',
    learning_duration: '6-12 Months',
    related_careers: ['Data Analyst', 'Cloud Engineer', 'DevOps Specialist', 'QA Automation Engineer']
  },
  {
    id: 'car_ui_ux_designer',
    career_name: 'UI/UX Designer',
    category: 'Technology & Data',
    description: 'Design intuitive, accessible digital experiences and user interfaces through user research, wireframing, and interactive prototyping.',
    interest_areas: ['Design', 'Creativity', 'Technology', 'Helping people', 'Psychology'],
    work_styles: ['creative', 'computer_based', 'people_oriented', 'indoor', 'balanced'],
    common_skills: ['Figma', 'User Research & Personas', 'Wireframing & Prototyping', 'Design Systems', 'Usability Testing', 'Information Architecture'],
    transferable_skills: ['User empathy', 'Visual aesthetics', 'Communication', 'Critique incorporation', 'Product thinking'],
    education_pathways: ['Design Degree (B.Des / Visual Arts)', 'Human-Computer Interaction coursework', 'Design portfolio with verified user case studies'],
    entry_pathways: ['Junior Product Designer', 'UI Designer', 'UX Researcher Assistant', 'Freelance Interface Designer'],
    learning_areas: ['Interaction design principles', 'Typography & design tokens', 'Usability testing & heuristic audits', 'Mobile-first responsive design'],
    practical_tasks: ['Redesign a confusing checkout flow and conduct 3 user walkthroughs', 'Create a complete design system with buttons, inputs, and modals in Figma', 'Produce high-fidelity clickable prototype'],
    portfolio_needs: ['Case study presentation detailing the problem, user research, wireframes, user testing feedback, and final polished design'],
    work_environment: ['Product design teams', 'Agencies', 'Fintech & Healthtech companies', 'Freelance / Remote'],
    hands_on_level: 'Low',
    computer_use_level: 'High',
    people_interaction_level: 'High',
    income_potential: 'High',
    learning_duration: '4-8 Months',
    related_careers: ['Graphic Designer', 'Frontend Developer', 'Product Manager', 'Design Researcher']
  },
  {
    id: 'car_qa_engineer',
    career_name: 'QA & Test Automation Engineer',
    category: 'Technology & Data',
    description: 'Ensure software quality, reliability, and security through systematic test planning, manual verification, and automated test scripts.',
    interest_areas: ['Technology', 'Computers', 'Problem Solving', 'Attention to detail'],
    work_styles: ['structured', 'analytical', 'computer_based', 'indoor', 'independent'],
    common_skills: ['Test Case Writing', 'Selenium / Cypress / Playwright', 'API Testing (Postman)', 'Bug Tracking (Jira)', 'CI/CD Pipelines'],
    transferable_skills: ['Attention to edge cases', 'Root-cause analysis', 'Clear technical writing', 'Patience & methodical testing'],
    education_pathways: ['Computer Science degree or IT diploma', 'Software testing certifications (ISTQB)', 'Practical automation repository'],
    entry_pathways: ['Junior QA Tester', 'Automation Test Engineer', 'Manual QA Specialist', 'SDET Trainee'],
    learning_areas: ['Software testing life cycle (STLC)', 'Automated browser test suites', 'API regression testing', 'Performance load testing'],
    practical_tasks: ['Write a comprehensive test plan for an e-commerce cart', 'Automate a login and search flow using Playwright', 'Inspect API response schemas with assertions'],
    portfolio_needs: ['GitHub repository with automated end-to-end test suite and bug report case study examples'],
    work_environment: ['Software companies', 'Fintech', 'Consulting firms', 'Remote'],
    hands_on_level: 'Low',
    computer_use_level: 'High',
    people_interaction_level: 'Moderate',
    income_potential: 'Good Growth',
    learning_duration: '3-6 Months',
    related_careers: ['Software Developer', 'DevOps Specialist', 'IT Support']
  },

  // 2. SKILLED TRADES (PRACTICAL / VOCATIONAL)
  {
    id: 'car_electrician',
    career_name: 'Licensed Electrician',
    category: 'Skilled Trades',
    description: 'Install, maintain, and repair electrical wiring, equipment, and distribution fixtures safely in residential, commercial, or industrial settings.',
    interest_areas: ['Electronics', 'Machines', 'Repair', 'Engineering', 'Practical Work'],
    work_styles: ['hands_on', 'structured', 'outdoor', 'indoor', 'balanced'],
    common_skills: ['Lockout/Tagout (LOTO)', 'Live-Dead-Live Testing', 'Multimeter Diagnostics', 'Electrical Code Compliance', 'Circuit Schematics', 'Conduit Bending'],
    transferable_skills: ['Physical dexterity', 'Safety discipline', 'Spatial reasoning', 'Practical troubleshooting', 'Customer communication'],
    education_pathways: ['Vocational ITI / Technical Diploma in Electrical', 'Government Wireman License / NSDC Certification', 'Supervised Trade Apprenticeship'],
    entry_pathways: ['Apprentice Electrician', 'Residential Wireman Assistant', 'Industrial Maintenance Helper', 'Substation Operator Assistant'],
    learning_areas: ['National Electrical Code (NEC/IS)', 'Three-phase power distributions', 'Overload & grounding protection', 'Commercial motor wiring'],
    practical_tasks: ['Perform 5-step voltage verification with calibrated meter', 'Wire a distribution board with MCB and ELCB protection', 'Diagnose motor starter relay failure'],
    portfolio_needs: ['Apprenticeship logbook, safety compliance badge, and verified trade testing records'],
    work_environment: ['Construction sites', 'Residential homes', 'Industrial manufacturing plants', 'Self-employed contractor'],
    hands_on_level: 'High',
    computer_use_level: 'Low',
    people_interaction_level: 'Moderate',
    income_potential: 'High',
    learning_duration: '6-18 Months',
    related_careers: ['Appliance Repair Technician', 'Solar Installation Specialist', 'HVAC Technician', 'Electrical Controls Engineer']
  },
  {
    id: 'car_appliance_technician',
    career_name: 'Appliance Repair Technician',
    category: 'Skilled Trades',
    description: 'Diagnose, service, and repair domestic and commercial appliances like refrigerators, washing machines, microwaves, and air conditioners.',
    interest_areas: ['Machines', 'Electronics', 'Repair', 'Helping people', 'Practical Work'],
    work_styles: ['hands_on', 'people_oriented', 'indoor', 'balanced', 'fast_changing'],
    common_skills: ['Appliance Circuit Diagnostics', 'Multimeter Continuity Checks', 'Motor & Capacitor Testing', 'Customer Quotations', 'Refrigerant Handling'],
    transferable_skills: ['Mechanical diagnostic mindset', 'Customer service', 'Punctuality', 'Safety protocols', 'Billing integrity'],
    education_pathways: ['Vocational ITI Refrigeration/Air Conditioning course', 'OEM brand technician certification (Samsung/LG/Whirlpool)', 'Practical workshop apprenticeship'],
    entry_pathways: ['Junior Service Tech', 'Authorized Service Center Assistant', 'Independent Repair Contractor'],
    learning_areas: ['Inverter motor drive mechanics', 'Compressor troubleshooting', 'Electronic control board (PCB) relays', 'Safe gas evacuation & brazing'],
    practical_tasks: ['Diagnose capacitor failure in a single-phase induction motor', 'Trace continuity on a washing machine drain pump circuit', 'Draft a clear repair invoice with parts and labor'],
    portfolio_needs: ['Trade competency card, verified service logbook, customer satisfaction records'],
    work_environment: ['Customer homes', 'Authorized brand repair centers', 'Local workshop', 'Self-employed vehicle'],
    hands_on_level: 'High',
    computer_use_level: 'Low',
    people_interaction_level: 'High',
    income_potential: 'Good Growth',
    learning_duration: '3-9 Months',
    related_careers: ['Licensed Electrician', 'HVAC Technician', 'Small Business Owner']
  },
  {
    id: 'car_hvac_technician',
    career_name: 'HVAC & Refrigeration Specialist',
    category: 'Skilled Trades',
    description: 'Install, service, and maintain heating, ventilation, air conditioning, and refrigeration systems for homes, malls, hospitals, and server rooms.',
    interest_areas: ['Machines', 'Engineering', 'Repair', 'Practical Work'],
    work_styles: ['hands_on', 'structured', 'indoor', 'outdoor', 'balanced'],
    common_skills: ['Thermodynamic Principles', 'Refrigerant Recovery & Charging', 'Air Duct Balancing', 'Electrical Controls', 'Brazing & Soldering'],
    transferable_skills: ['Thermal diagnostics', 'Tool proficiency', 'Safety consciousness', 'Physical fitness'],
    education_pathways: ['ITI Air Conditioning & Refrigeration Trade Diploma', 'EPA / National Refrigerant Handling Certification', 'Trade Apprenticeship'],
    entry_pathways: ['HVAC Apprentice', 'Field Service Technician', 'Commercial Chiller Operator Assistant'],
    learning_areas: ['Vapor compression cycles', 'Digital manifold gauge reading', 'Variable refrigerant flow (VRF) systems', 'Preventative maintenance'],
    practical_tasks: ['Recover refrigerant safely using recovery unit', 'Test compressor winding resistance against spec sheet', 'Balance airflow across room dampers'],
    portfolio_needs: ['EPA/NSDC trade credentials, safety training certification, apprenticeship completion record'],
    work_environment: ['Commercial buildings', 'Cold storage facilities', 'Residential complexes', 'Data centers'],
    hands_on_level: 'High',
    computer_use_level: 'Low',
    people_interaction_level: 'Moderate',
    income_potential: 'High',
    learning_duration: '6-12 Months',
    related_careers: ['Licensed Electrician', 'Appliance Repair Technician', 'Facility Maintenance Manager']
  },
  {
    id: 'car_welder_fabricator',
    career_name: 'Precision Welder & Fabricator',
    category: 'Skilled Trades',
    description: 'Cut, shape, and join metal components using MIG, TIG, and arc welding techniques according to engineering specifications and safety codes.',
    interest_areas: ['Machines', 'Construction', 'Engineering', 'Practical Work'],
    work_styles: ['hands_on', 'structured', 'indoor', 'independent'],
    common_skills: ['MIG / TIG / SMAW Welding', 'Blueprint & Schematic Reading', 'Metal Cutting & Grinding', 'Joint Fit-up Inspection', 'PPE & Heat Hazard Control'],
    transferable_skills: ['Hand-eye coordination', 'Spatial precision', 'Material science awareness', 'Quality patience'],
    education_pathways: ['Vocational ITI Welder Trade Certificate', 'AWS / ISO Welder Qualification Test', 'Industrial Fabrication Apprenticeship'],
    entry_pathways: ['Welding Apprentice', 'Structural Fabricator Helper', 'Pipe Welder Trainee'],
    learning_areas: ['Metallurgy of ferrous & non-ferrous metals', 'Weld defect inspection (porosity, undercut)', 'Gas flow regulation', 'Structural joint angles'],
    practical_tasks: ['Produce a clean multi-pass TIG fillet weld', 'Perform visual dye-penetrant inspection on a butt weld', 'Fabricate a steel bracket from a technical drawing'],
    portfolio_needs: ['Welder qualification test test-piece certifications, safety compliance record'],
    work_environment: ['Manufacturing plants', 'Construction sites', 'Shipyards', 'Automotive fabrication shops'],
    hands_on_level: 'High',
    computer_use_level: 'Low',
    people_interaction_level: 'Low',
    income_potential: 'High',
    learning_duration: '6-12 Months',
    related_careers: ['Mechanical CAD Specialist', 'Automotive Technician', 'Construction Supervisor']
  },

  // 3. HEALTHCARE & LIFE SCIENCES
  {
    id: 'car_clinical_nurse',
    career_name: 'Registered / Clinical Nurse',
    category: 'Healthcare & Life Sciences',
    description: 'Deliver compassionate patient care, monitor clinical conditions, administer prescribed treatments, and educate individuals and families.',
    interest_areas: ['Healthcare', 'Helping people', 'Science', 'Communication'],
    work_styles: ['people_oriented', 'structured', 'indoor', 'fast_changing', 'team'],
    common_skills: ['Patient Vital Monitoring', 'Medication Administration', 'Infection Control Protocols', 'Emergency First Aid & CPR', 'Electronic Health Records (EHR)'],
    transferable_skills: ['Deep empathy', 'Critical decision making under pressure', 'Clear verbal handover', 'Active observation'],
    education_pathways: ['B.Sc Nursing / General Nursing & Midwifery (GNM) Diploma', 'State Nursing Council Registration & License', 'Supervised Clinical Practicum'],
    entry_pathways: ['Staff Nurse', 'Ward Care Specialist', 'ICU Trainee Nurse', 'Community Health Care Assistant'],
    learning_areas: ['Human anatomy & physiology', 'Pharmacology & dosage calculations', 'Clinical triage protocols', 'Patient privacy & medical ethics'],
    practical_tasks: ['Accurately measure and chart 4 vital signs', 'Practice sterile wound dressing change sequence', 'Deliver SBAR clinical handover script in practice studio'],
    portfolio_needs: ['Accredited nursing council registration, clinical rotation logs, BLS/ACLS certification'],
    work_environment: ['Hospitals', 'Emergency wards', 'Community health centers', 'Home health agencies'],
    hands_on_level: 'High',
    computer_use_level: 'Moderate',
    people_interaction_level: 'High',
    income_potential: 'High',
    learning_duration: '2-4 Years (Formal Pathway)',
    related_careers: ['Healthcare Administrator', 'Medical Laboratory Technician', 'Public Health Educator']
  },
  {
    id: 'car_med_lab_technician',
    career_name: 'Medical Laboratory Technician',
    category: 'Healthcare & Life Sciences',
    description: 'Perform diagnostic laboratory tests on clinical samples using automated analyzers and microscopes to assist physicians in patient diagnosis.',
    interest_areas: ['Healthcare', 'Science', 'Research', 'Computers'],
    work_styles: ['analytical', 'structured', 'indoor', 'independent', 'hands_on'],
    common_skills: ['Blood Sample Processing', 'Clinical Biochemistry', 'Hematology Analysis', 'Microscope Calibration', 'Sterilization & Biohazard Protocols'],
    transferable_skills: ['Extreme precision', 'Sterile hygiene discipline', 'Analytical record keeping', 'Systematic calibration'],
    education_pathways: ['Diploma in Medical Laboratory Technology (DMLT)', 'B.Sc Medical Laboratory Science', 'National Paramedical Council Certification'],
    entry_pathways: ['Junior Lab Technician', 'Phlebotomy Technician', 'Pathology Lab Assistant'],
    learning_areas: ['Specimen collection & preservation', 'Diagnostic reagents & standard curves', 'Quality control (Levey-Jennings charts)', 'Biohazard disposal protocols'],
    practical_tasks: ['Prepare and focus a peripheral blood smear under oil immersion', 'Calibrate an automated chemistry analyzer with control serum', 'Identify critical abnormal values and report protocol'],
    portfolio_needs: ['DMLT diploma, certified internship logbook from an accredited hospital lab'],
    work_environment: ['Diagnostic diagnostic centers', 'Hospital pathology departments', 'Blood banks', 'Research laboratories'],
    hands_on_level: 'High',
    computer_use_level: 'Moderate',
    people_interaction_level: 'Low',
    income_potential: 'Good Growth',
    learning_duration: '1-2 Years',
    related_careers: ['Pharmacy Technician', 'Healthcare Administrator', 'Clinical Research Associate']
  },
  {
    id: 'car_healthcare_admin',
    career_name: 'Healthcare Operations & Patient Administrator',
    category: 'Healthcare & Life Sciences',
    description: 'Coordinate hospital admissions, patient scheduling, billing workflows, and compliance records to keep clinical facilities operating smoothly.',
    interest_areas: ['Healthcare', 'Business', 'Helping people', 'Organization'],
    work_styles: ['people_oriented', 'structured', 'computer_based', 'indoor', 'team'],
    common_skills: ['Hospital Information Systems (HIS)', 'Medical Billing & Insurance Codes', 'Patient Scheduling', 'Compliance & HIPAA / NABH Standards', 'Patient Relations'],
    transferable_skills: ['Empathetic conflict resolution', 'Organizational coordination', 'Clear written communication', 'Data confidentiality'],
    education_pathways: ['BBA / MBA / Diploma in Hospital Administration', 'Degree in Health Information Management', 'Healthcare billing certifications'],
    entry_pathways: ['Patient Care Coordinator', 'Hospital Front Office Executive', 'Medical Billing Associate', 'Health Insurance Desk Officer'],
    learning_areas: ['Healthcare service operations', 'Insurance pre-authorization and claims', 'Hospital accreditation quality standards', 'Medical terminology'],
    practical_tasks: ['Draft an empathetic patient intake and admission form', 'Walk through an insurance claim query with documentation checklist', 'Calculate bed occupancy and patient turnaround metrics'],
    portfolio_needs: ['Healthcare administration internship case study, hospital system certifications'],
    work_environment: ['Multi-specialty hospitals', 'Outpatient clinics', 'Health insurance firms', 'Diagnostic chains'],
    hands_on_level: 'Low',
    computer_use_level: 'High',
    people_interaction_level: 'High',
    income_potential: 'High',
    learning_duration: '6-12 Months',
    related_careers: ['Operations Coordinator', 'Customer Success Specialist', 'Clinical Nurse']
  },

  // 4. MARKETING, SALES & CUSTOMER
  {
    id: 'car_digital_marketer',
    career_name: 'Digital Growth Marketer',
    category: 'Marketing & Customer',
    description: 'Design and execute multi-channel digital campaigns across SEO, social media, paid advertising, and email automation to drive measurable growth.',
    interest_areas: ['Marketing', 'Business', 'Creativity', 'Technology', 'Communication'],
    work_styles: ['creative', 'analytical', 'computer_based', 'indoor', 'fast_changing'],
    common_skills: ['Google Analytics 4', 'Search Engine Optimization (SEO)', 'Meta Ads / Google Search Ads', 'Content Strategy', 'Conversion Rate Optimization (CRO)', 'Email Marketing'],
    transferable_skills: ['Customer empathy', 'Hypothesis testing', 'Copywriting', 'Budget management', 'Data storytelling'],
    education_pathways: ['Degree in Marketing / Business / Mass Comm / Any discipline', 'Google / Meta certified digital marketing programs', 'Live portfolio of campaigns and case studies'],
    entry_pathways: ['Digital Marketing Executive', 'SEO Specialist', 'Social Media Manager', 'Performance Marketing Associate'],
    learning_areas: ['Marketing funnel economics (CAC, LTV, ROAS)', 'Technical SEO audit frameworks', 'Ad copy testing frameworks', 'Email drip sequences'],
    practical_tasks: ['Perform a comprehensive SEO audit of a live competitor website', 'Plan a $500 monthly ad spend allocation with target audience personas', 'Write 3 high-converting email sequences for a product onboarding flow'],
    portfolio_needs: ['Live campaign case study highlighting traffic growth, conversion rates, and creative ad copies on a portfolio website'],
    work_environment: ['Digital marketing agencies', 'E-commerce companies', 'B2B SaaS startups', 'Freelance / Remote'],
    hands_on_level: 'Low',
    computer_use_level: 'High',
    people_interaction_level: 'Moderate',
    income_potential: 'High',
    learning_duration: '3-6 Months',
    related_careers: ['Content Strategist', 'UI/UX Designer', 'Sales Representative', 'Data Analyst']
  },
  {
    id: 'car_customer_success',
    career_name: 'Customer Success & Product Specialist',
    category: 'Marketing & Customer',
    description: 'Ensure client adoption, retention, and satisfaction by guiding users through software onboarding, resolving workflow bottlenecks, and driving renewals.',
    interest_areas: ['Helping people', 'Communication', 'Technology', 'Business'],
    work_styles: ['people_oriented', 'computer_based', 'indoor', 'balanced', 'team'],
    common_skills: ['Customer Onboarding Workflows', 'CRM & Ticket Tools (HubSpot, Zendesk)', 'Product Demos', 'Retention & Churn Analysis', 'Cross-functional Advocacy'],
    transferable_skills: ['Active listening', 'De-escalation under tension', 'Technical problem translation', 'Relationship building'],
    education_pathways: ['Any undergraduate degree (Arts, Science, Commerce, Engineering)', 'Customer support to CS career transition', 'Client relationship certifications'],
    entry_pathways: ['Customer Support Specialist', 'Customer Success Associate', 'Account Manager Trainee', 'Product Support Specialist'],
    learning_areas: ['Net Promoter Score (NPS) & Customer Health Scores', 'Quarterly business review (QBR) deck preparation', 'Software implementation mapping'],
    practical_tasks: ['De-escalate an upset enterprise client via a structured response email', 'Create a 5-step customer onboarding checklist for a new software account', 'Analyze customer churn feedback and summarize 3 product recommendations'],
    portfolio_needs: ['STAR-format case studies of successful client renewals and retention improvements'],
    work_environment: ['SaaS technology firms', 'Subscription service companies', 'Fintech platforms', 'Remote'],
    hands_on_level: 'Low',
    computer_use_level: 'High',
    people_interaction_level: 'High',
    income_potential: 'High',
    learning_duration: '2-4 Months',
    related_careers: ['Digital Growth Marketer', 'Sales Representative', 'Operations Coordinator', 'Healthcare Administrator']
  },

  // 5. BUSINESS & ENTREPRENEURSHIP
  {
    id: 'car_operations_coordinator',
    career_name: 'Operations & Logistics Coordinator',
    category: 'Business & Management',
    description: 'Streamline daily business processes, supply logistics, vendor communication, and team schedules to ensure reliable company execution.',
    interest_areas: ['Business', 'Organization', 'Communication', 'Problem Solving'],
    work_styles: ['structured', 'balanced', 'people_oriented', 'indoor', 'fast_changing'],
    common_skills: ['Process Optimization', 'Vendor Negotiation', 'ERP / Inventory Software', 'Resource Scheduling', 'SLA Monitoring', 'Cost Tracking'],
    transferable_skills: ['Crisis troubleshooting', 'Time management', 'Coordination', 'Attention to operational bottlenecks'],
    education_pathways: ['Degree in Business Administration, Commerce, Engineering, or practical operations experience', 'Lean / Six Sigma Yellow Belt'],
    entry_pathways: ['Operations Associate', 'Supply Chain Coordinator', 'Office Operations Executive', 'Fulfillment Supervisor'],
    learning_areas: ['Standard operating procedure (SOP) design', 'Inventory reorder levels & safety stock', 'Vendor evaluation metrics', 'Cross-departmental tracking'],
    practical_tasks: ['Write a 1-page Standard Operating Procedure (SOP) for vendor onboarding', 'Map out a fulfillment bottleneck and propose a 20% faster workflow', 'Calculate weekly operational cost variance against budget'],
    portfolio_needs: ['Documented process optimization artifacts, SOP portfolios, verifiable operational milestones'],
    work_environment: ['Logistics hubs', 'Retail chains', 'Startups', 'Manufacturing offices'],
    hands_on_level: 'Moderate',
    computer_use_level: 'Moderate',
    people_interaction_level: 'High',
    income_potential: 'High',
    learning_duration: '3-6 Months',
    related_careers: ['Healthcare Administrator', 'Customer Success Specialist', 'Small Business Owner', 'Project Coordinator']
  },
  {
    id: 'car_entrepreneur',
    career_name: 'Small Business Entrepreneur / Founder',
    category: 'Entrepreneurship / Freelancing',
    description: 'Identify customer pain points, validate market demand, build lean minimum viable products (MVPs), and operate a viable sustainable enterprise.',
    interest_areas: ['Business', 'Entrepreneurship', 'Creativity', 'Problem Solving', 'Leadership'],
    work_styles: ['fast_changing', 'creative', 'people_oriented', 'balanced', 'hands_on'],
    common_skills: ['Customer Discovery & Interviews', 'Lean MVP Prototyping', 'Basic Unit Economics', 'Sales & Pitching', 'Cashflow Budgeting', 'Digital Storefronts'],
    transferable_skills: ['Grit & resilience', 'Calculated risk-taking', 'Decisiveness', 'Resourcefulness', 'Storytelling'],
    education_pathways: ['Practical experience & market trial', 'Business courses / incubation programs', 'Mentorship-guided venture building'],
    entry_pathways: ['Solo Service Operator', 'Local Retail / Workshop Founder', 'Digital Freelancer / Agency Owner', 'Product Startup Founder'],
    learning_areas: ['Lean startup customer interview techniques', 'Cost-of-goods-sold (COGS) vs gross margin calculation', 'Initial customer acquisition tactics', 'Regulatory registration basics'],
    practical_tasks: ['Interview 5 prospective customers about an acute pain point', 'Calculate 30-day startup budget and break-even sales requirements', 'Build a 1-page landing flyer or social offer to test pre-order interest'],
    portfolio_needs: ['Completed business model canvas, customer interview evidence, verified pilot revenue or pre-orders'],
    work_environment: ['Local market / workshop', 'Co-working space', 'Client job sites', 'Home office'],
    hands_on_level: 'Moderate',
    computer_use_level: 'Moderate',
    people_interaction_level: 'High',
    income_potential: 'High',
    learning_duration: 'Ongoing / Fast-Action',
    related_careers: ['Operations Coordinator', 'Digital Growth Marketer', 'Licensed Electrician', 'Graphic Designer']
  },

  // 6. DESIGN & CREATIVE
  {
    id: 'car_graphic_designer',
    career_name: 'Graphic Designer & Visual Brand Creator',
    category: 'Design & Creative',
    description: 'Craft compelling brand visual identities, marketing collateral, social media assets, and print materials that communicate ideas with clarity.',
    interest_areas: ['Design', 'Creativity', 'Writing', 'Technology'],
    work_styles: ['creative', 'computer_based', 'indoor', 'independent', 'balanced'],
    common_skills: ['Adobe Illustrator / Photoshop', 'Figma / Canva Pro', 'Typography & Grid Systems', 'Brand Style Guides', 'Color Theory', 'Print Pre-press Basics'],
    transferable_skills: ['Visual visual judgment', 'Attention to visual details', 'Client brief translation', 'Creative adaptability'],
    education_pathways: ['Degree/Diploma in Fine Arts / Visual Communication', 'Self-taught with disciplined design community portfolio (Behance/Dribbble)'],
    entry_pathways: ['Junior Graphic Designer', 'Brand Identity Designer', 'Social Media Creative Executive', 'Freelance Visual Designer'],
    learning_areas: ['Visual hierarchy & balance', 'Logo design & vector precision', 'Social media ad format guidelines', 'Print export resolutions & bleed'],
    practical_tasks: ['Design a complete 3-color brand logo and identity board for a local bakery', 'Create a 4-carousel educational Instagram graphics set', 'Design an event poster using structured typographic hierarchy'],
    portfolio_needs: ['Curated Behance or personal portfolio with 4-6 diverse branding and collateral projects with design rationales'],
    work_environment: ['Design studios', 'Advertising agencies', 'Corporate marketing teams', 'Freelance / Home studio'],
    hands_on_level: 'Low',
    computer_use_level: 'High',
    people_interaction_level: 'Moderate',
    income_potential: 'Good Growth',
    learning_duration: '3-6 Months',
    related_careers: ['UI/UX Designer', 'Video Producer', 'Digital Growth Marketer']
  },
  {
    id: 'car_video_producer',
    career_name: 'Video Producer & Multimedia Editor',
    category: 'Design & Creative',
    description: 'Record, edit, color-grade, and package engaging video content for YouTube, commercial ads, corporate training, and social media reels.',
    interest_areas: ['Creativity', 'Technology', 'Storytelling', 'Computers'],
    work_styles: ['creative', 'computer_based', 'indoor', 'fast_changing', 'hands_on'],
    common_skills: ['Premiere Pro / DaVinci Resolve', 'Audio Mixing & Sound Design', 'Pacing & Narrative Storytelling', 'Color Grading', 'Basic Motion Graphics (After Effects)'],
    transferable_skills: ['Story flow intuition', 'Patience during revision cycles', 'Visual framing', 'Multi-task media management'],
    education_pathways: ['Film / Media Degree or Vocational Editing Diploma', 'Hands-on portfolio of edited YouTube/Reels content'],
    entry_pathways: ['Assistant Video Editor', 'Social Media Video Creator', 'Content Studio Editor', 'Freelance Videographer'],
    learning_areas: ['Cutting on action and visual rhythm', 'Audio equalization & noise reduction', 'Keyframing motion graphics & lower thirds', 'Multi-camera sync'],
    practical_tasks: ['Edit raw interview footage with B-roll cutaways and subtitles', 'Produce a 30-second high-energy vertical promotional reel', 'Color-grade flat log footage to natural skin tones'],
    portfolio_needs: ['A 60-second edited video showreel demonstrating pacing, storytelling, sound design, and color work'],
    work_environment: ['Production houses', 'Content creator agencies', 'Marketing departments', 'Freelance'],
    hands_on_level: 'Moderate',
    computer_use_level: 'High',
    people_interaction_level: 'Moderate',
    income_potential: 'High',
    learning_duration: '3-6 Months',
    related_careers: ['Graphic Designer', 'UI/UX Designer', 'Digital Growth Marketer']
  },

  // 7. EDUCATION & TRAINING
  {
    id: 'car_technical_trainer',
    career_name: 'Practical Technical & Vocational Trainer',
    category: 'Education & Training',
    description: 'Empower students, apprentices, and corporate teams by translating complex technical skills, trade safety, and practical tools into clear interactive lessons.',
    interest_areas: ['Teaching', 'Helping people', 'Communication', 'Technology', 'Engineering'],
    work_styles: ['people_oriented', 'structured', 'indoor', 'balanced', 'hands_on'],
    common_skills: ['Curriculum Planning', 'Hands-on Demonstrations', 'Student Assessment Design', 'Workshop Safety Instruction', 'Mentorship & Feedback Delivery'],
    transferable_skills: ['Patient explanation', 'Public speaking', 'Breaking down complex concepts', 'Encouragement and mentoring'],
    education_pathways: ['Subject domain expertise (Engineering / Trades / IT / Healthcare)', 'Trainer of Trainers (ToT) Certification', 'B.Ed or Vocational Instructor Training (CITS)'],
    entry_pathways: ['Vocational Instructor', 'Technical Lab Trainer', 'Corporate Skill Development Facilitator', 'Online Course Instructor'],
    learning_areas: ['Adult learning principles (Andragogy)', 'Formative vs summative skill assessments', 'Safe lab supervision checklists', 'Interactive classroom engagement'],
    practical_tasks: ['Prepare a 30-minute structured lesson plan with a hands-on exercise', 'Conduct a mock demonstration explaining a core tool or code concept clearly in Practice Studio', 'Draft a 10-question rubric to evaluate student project competency'],
    portfolio_needs: ['Recorded micro-teaching demonstration, sample curriculum plan, learner feedback ratings'],
    work_environment: ['Vocational training institutes', 'Colleges & universities', 'Corporate training academies', 'EdTech platforms'],
    hands_on_level: 'High',
    computer_use_level: 'Moderate',
    people_interaction_level: 'High',
    income_potential: 'Good Growth',
    learning_duration: '6-12 Months',
    related_careers: ['School Educator', 'Human Mentor', 'Software Developer', 'Licensed Electrician']
  },

  // 8. AGRICULTURE & FOOD
  {
    id: 'car_agribusiness_manager',
    career_name: 'Precision Agriculture & Farm Operations Manager',
    category: 'Agriculture & Food',
    description: 'Manage crop production cycles, modern irrigation systems, soil nutrition, and produce marketing to run productive, sustainable agricultural operations.',
    interest_areas: ['Agriculture', 'Food', 'Machines', 'Business', 'Outdoor'],
    work_styles: ['hands_on', 'outdoor', 'structured', 'balanced', 'independent'],
    common_skills: ['Soil & Crop Nutrition', 'Drip & Precision Irrigation', 'Pest Management Protocols', 'Farm Equipment Maintenance', 'Produce Supply Chain & Sales'],
    transferable_skills: ['Weather adaptability', 'Long-term planning', 'Operational resilience', 'Cost tracking'],
    education_pathways: ['B.Sc Agriculture / Horticulture / Agricultural Engineering', 'Vocational Krishi Vigyan Kendra (KVK) diplomas', 'Hands-on generational farm management experience'],
    entry_pathways: ['Farm Supervisor', 'Greenhouse Technician', 'Agronomist Field Associate', 'Organic Farm Entrepreneur'],
    learning_areas: ['Crop schedule planning', 'Soil pH and organic matter enrichment', 'Government agricultural subsidies & FPO marketing', 'Post-harvest storage'],
    practical_tasks: ['Calculate fertilizer dosage requirements per acre for a seasonal crop', 'Design an automated drip irrigation valve schedule', 'Draft a direct-to-consumer farm produce pricing strategy'],
    portfolio_needs: ['Field management logbooks, soil audit records, produce yield improvement documentation'],
    work_environment: ['Commercial farms', 'Greenhouses & nurseries', 'Agricultural producer cooperatives', 'Outdoor fields'],
    hands_on_level: 'High',
    computer_use_level: 'Low',
    people_interaction_level: 'Moderate',
    income_potential: 'High',
    learning_duration: '6-18 Months',
    related_careers: ['Food Processing Specialist', 'Operations Coordinator', 'Small Business Owner']
  },

  // 9. FINANCE & ACCOUNTING
  {
    id: 'car_accounting_associate',
    career_name: 'Accounting & Tax Associate',
    category: 'Finance & Accounting',
    description: 'Maintain accurate financial ledgers, balance accounts, prepare GST and tax filings, and generate financial reports for businesses and individuals.',
    interest_areas: ['Finance', 'Business', 'Computers', 'Mathematics'],
    work_styles: ['structured', 'analytical', 'computer_based', 'indoor', 'independent'],
    common_skills: ['Tally / QuickBooks / Zoho Books', 'Double-Entry Bookkeeping', 'GST / VAT Compliance', 'Financial Statements (P&L, Balance Sheet)', 'Bank Reconciliation'],
    transferable_skills: ['Mathematical precision', 'Confidentiality', 'Methodical organization', 'Regulatory adherence'],
    education_pathways: ['B.Com / BBA in Finance', 'Accounting software certifications (Tally/QuickBooks)', 'Chartered Accountancy (CA) / CPA intermediate studies'],
    entry_pathways: ['Junior Accountant', 'Accounts Payable/Receivable Clerk', 'Tax Filing Assistant', 'Audit Assistant'],
    learning_areas: ['Ledger reconciliation and trail balance', 'Statutory tax deductions (TDS, GST)', 'Depreciation schedules', 'Cashflow statements'],
    practical_tasks: ['Reconcile 30 days of bank transactions against company ledger', 'Calculate GST tax liability and input tax credit (ITC) for a quarterly return', 'Draft a basic profit & loss statement from unadjusted ledger accounts'],
    portfolio_needs: ['Accounting certification transcripts, completed mock financial ledger audits on Excel/Tally'],
    work_environment: ['Accounting firms', 'Corporate finance departments', 'Small businesses', 'Independent practice'],
    hands_on_level: 'Low',
    computer_use_level: 'High',
    people_interaction_level: 'Moderate',
    income_potential: 'High',
    learning_duration: '4-8 Months',
    related_careers: ['Data Analyst', 'Operations Coordinator', 'Financial Analyst']
  },

  // 10. COMMUNITY & SOCIAL
  {
    id: 'car_community_coordinator',
    career_name: 'Community Development & NGO Coordinator',
    category: 'Community / Social',
    description: 'Coordinate grassroots welfare programs, vocational training workshops, beneficiary outreach, and grant reporting for non-profits and community organizations.',
    interest_areas: ['Helping people', 'Community', 'Communication', 'Organization'],
    work_styles: ['people_oriented', 'hands_on', 'balanced', 'fast_changing', 'team'],
    common_skills: ['Community Outreach & Mobilization', 'Beneficiary Survey Design', 'Grant & Project Reporting', 'Workshop Facilitation', 'Stakeholder Networking'],
    transferable_skills: ['Deep cultural empathy', 'Grassroots communication', 'Conflict mediation', 'Resourceful problem solving'],
    education_pathways: ['Master or Bachelor in Social Work (MSW / BSW) or Sociology / Humanities', 'Grassroots volunteer and fieldwork experience'],
    entry_pathways: ['Field Officer', 'Program Coordinator', 'Community Mobilizer', 'NGO Project Assistant'],
    learning_areas: ['Participatory rural appraisal (PRA) tools', 'Government social welfare scheme eligibility', 'Grant impact metrics and reporting', 'Volunteer management'],
    practical_tasks: ['Conduct a community needs assessment survey with 10 local families', 'Draft a 2-page project proposal for a rural youth vocational workshop', 'Organize and facilitate a community health or safety awareness session'],
    portfolio_needs: ['Field impact case studies, program reports with beneficiary feedback testimonies'],
    work_environment: ['NGOs and foundations', 'Rural and urban community centers', 'Government development boards', 'Field sites'],
    hands_on_level: 'Moderate',
    computer_use_level: 'Moderate',
    people_interaction_level: 'High',
    income_potential: 'Good Growth',
    learning_duration: '3-6 Months',
    related_careers: ['Healthcare Administrator', 'Technical Trainer', 'Operations Coordinator']
  },

  // 11. SKILLED TRADES EXPANSIONS
  {
    id: 'car_plumber',
    career_name: 'Licensed Plumber & Piping Systems Specialist',
    category: 'Skilled Trades',
    description: 'Install, inspect, and maintain potable water, drainage, venting, and hydronic heating systems complying with local plumbing codes.',
    interest_areas: ['Repair', 'Machines', 'Hands-on', 'Practical Work', 'Construction'],
    work_styles: ['hands_on', 'independent', 'structured', 'physical', 'problem_solving'],
    common_skills: ['Pipe Fitting & Soldering', 'Drain Waste Vent (DWV) Systems', 'Water Pressure Regulators', 'Backflow Prevention', 'Blueprint Reading'],
    transferable_skills: ['Mechanical diagnostic reasoning', 'Safety protocol execution', 'Spatial layout analysis', 'Customer service'],
    education_pathways: ['Plumbing Vocational Certificate / ITI', 'Registered Apprenticeship Program', 'Journeyman Licensing Exam'],
    entry_pathways: ['Apprentice Plumber', 'Drain Service Technician', 'Residential Service Plumber', 'Commercial Pipefitter'],
    learning_areas: ['Soldering copper & pressing PEX', 'Pressure testing DWV pipelines', 'Water heater troubleshooting', 'Sizing pipe schedules'],
    practical_tasks: ['Pressure test a DWV pipe assembly to 5 PSI', 'Measure, cut, and sweat a 3/4" copper pipe fitting without leaks', 'Diagnose temperature-pressure relief valve malfunction'],
    portfolio_needs: ['Plumbing code inspection checklist records, apprenticeship work log with verified supervisor signatures'],
    work_environment: ['Residential homes', 'Commercial buildings', 'Construction sites', 'Municipal utility services'],
    hands_on_level: 'High',
    computer_use_level: 'Low',
    people_interaction_level: 'Moderate',
    income_potential: 'High',
    learning_duration: '6-12 Months',
    related_careers: ['Licensed Electrician', 'HVAC Specialist', 'Appliance Repair Technician']
  },
  {
    id: 'car_carpenter',
    career_name: 'Finish Carpenter & Architectural Woodworker',
    category: 'Skilled Trades',
    description: 'Fabricate, install, and finish custom cabinetry, trim, moldings, doors, and timber framing with precision craft and safety.',
    interest_areas: ['Design', 'Repair', 'Hands-on', 'Craftsmanship', 'Architecture'],
    work_styles: ['hands_on', 'creative', 'structured', 'detail_oriented'],
    common_skills: ['Miter Saw & Router Operation', 'Cabinetry Joinery', 'Architectural Blueprints', 'Material Selection & Moisture Testing', 'Laser Level Alignment'],
    transferable_skills: ['Extreme precision & measurement', 'Geometric spatial reasoning', 'Patience & craftsmanship', 'Material estimation'],
    education_pathways: ['Carpentry & Joinery Vocational Diploma', 'Carpentry Apprenticeship Guild', 'Hands-on woodshop portfolio'],
    entry_pathways: ['Rough Framing Assistant', 'Finish Carpentry Apprentice', 'Custom Cabinetmaker', 'Trim Specialist'],
    learning_areas: ['Compound miter cuts and coped joints', 'Drawer slide & hinge installation', 'Pneumatic fastening & safety', 'Hardwood finishing and stains'],
    practical_tasks: ['Cut and fit a 45-degree coped crown molding corner with zero gap', 'Fabricate a dovetailed hardwood drawer box with soft-close runners', 'Construct a plumb, level interior partition frame'],
    portfolio_needs: ['Photographic portfolio of 4 installed woodcraft projects showing tight joinery and smooth finishes'],
    work_environment: ['Custom woodshops', 'Residential renovation sites', 'Commercial millwork studios'],
    hands_on_level: 'High',
    computer_use_level: 'Low',
    people_interaction_level: 'Low',
    income_potential: 'Good Growth',
    learning_duration: '6-12 Months',
    related_careers: ['Precision Welder', 'Appliance Repair Technician', 'UI/UX Designer']
  },

  // 12. TECHNOLOGY & DATA EXPANSION
  {
    id: 'car_it_support',
    career_name: 'IT Support & Systems Administrator',
    category: 'Technology & Data',
    description: 'Resolve hardware, software, cloud access, and network infrastructure issues to keep teams productive, secure, and operational.',
    interest_areas: ['Technology', 'Computers', 'Helping people', 'Problem Solving'],
    work_styles: ['analytical', 'computer_based', 'people_oriented', 'structured', 'balanced'],
    common_skills: ['Operating Systems (Windows/macOS/Linux)', 'TCP/IP & LAN/WiFi Networking', 'Active Directory / Identity Management', 'Ticket Management (Jira/ServiceNow)', 'Hardware Troubleshooting & MDM'],
    transferable_skills: ['Patient customer communication', 'Step-by-step root cause analysis', 'Documentation clarity', 'Calm prioritization under pressure'],
    education_pathways: ['CompTIA A+ / Network+ Certification', 'Diploma in Computer Applications / Networking', 'Practical helpdesk troubleshooting experience'],
    entry_pathways: ['Helpdesk Tier 1 Technician', 'Desktop Support Specialist', 'Junior Systems Administrator', 'IT Operations Associate'],
    learning_areas: ['DHCP, DNS, and IP subnetting', 'Endpoint deployment & disk cloning', 'Password & MFA authentication resets', 'Disaster recovery backups'],
    practical_tasks: ['Diagnose a network connectivity failure using ping, traceroute, and nslookup', 'Create an automated user onboarding checklist in Active Directory', 'Rebuild and configure an OS image with standard corporate security software'],
    portfolio_needs: ['Technical SOP documentation for 3 troubleshooting scenarios, verified CompTIA or Google IT certificates'],
    work_environment: ['Corporate IT departments', 'Managed Service Providers (MSPs)', 'Educational institutions', 'Remote IT support centers'],
    hands_on_level: 'Moderate',
    computer_use_level: 'High',
    people_interaction_level: 'High',
    income_potential: 'Good Growth',
    learning_duration: '3-6 Months',
    related_careers: ['QA & Test Automation Engineer', 'Software Developer', 'Data Analyst']
  },

  // 13. MARKETING & SALES EXPANSIONS
  {
    id: 'car_content_marketing',
    career_name: 'Content Marketing & Copywriting Specialist',
    category: 'Marketing & Customer',
    description: 'Produce high-converting blog articles, email nurture campaigns, social storytelling, and educational assets that drive organic customer acquisition.',
    interest_areas: ['Writing', 'Creativity', 'Marketing', 'Communication', 'Business'],
    work_styles: ['creative', 'computer_based', 'independent', 'analytical'],
    common_skills: ['SEO Copywriting', 'Editorial Calendar Planning', 'Email Sequence Writing', 'Keyword Research', 'Content Management Systems (WordPress/Webflow)'],
    transferable_skills: ['Compelling written narrative', 'Audience empathy', 'Research rigor', 'Message clarity'],
    education_pathways: ['Degree in English, Journalism, Mass Communication, or Business', 'Verified public content portfolio / Substack', 'HubSpot Content Marketing Certification'],
    entry_pathways: ['Junior Content Writer', 'Copywriting Intern', 'SEO Content Specialist', 'Freelance Tech Writer'],
    learning_areas: ['Search intent & keyword clustering', 'Direct response copywriting hooks', 'Distribution across social channels', 'Email newsletter engagement'],
    practical_tasks: ['Write a 1,500-word SEO article targeting a high-intent commercial keyword with 80+ readability score', 'Draft a 5-part automated email welcome sequence with 40%+ open rate hooks', 'Audit 3 competitor blog libraries and identify 5 high-opportunity content gaps'],
    portfolio_needs: ['Live published writing samples across 3 distinct formats (long-form guide, email sequence, landing page hero)'],
    work_environment: ['Digital marketing agencies', 'SaaS tech companies', 'E-commerce brands', 'Remote / Freelance'],
    hands_on_level: 'Low',
    computer_use_level: 'High',
    people_interaction_level: 'Moderate',
    income_potential: 'High',
    learning_duration: '3-6 Months',
    related_careers: ['Digital Growth Marketer', 'Customer Success Specialist', 'Graphic Designer']
  },
  {
    id: 'car_sales_b2b',
    career_name: 'B2B Sales & Business Development Representative',
    category: 'Marketing & Customer',
    description: 'Identify target accounts, initiate consultative conversations, qualify prospective clients, and build recurring revenue pipelines for businesses.',
    interest_areas: ['Business', 'Sales', 'Communication', 'Negotiation', 'Helping people'],
    work_styles: ['people_oriented', 'fast_changing', 'structured', 'results_driven'],
    common_skills: ['Cold Outreach & Prospecting', 'Consultative Discovery Questions', 'CRM Management (Salesforce/HubSpot)', 'Objection Handling', 'Value Proposition Pitching'],
    transferable_skills: ['High emotional intelligence', 'Resilience & persistence', 'Active listening', 'Persuasive articulation'],
    education_pathways: ['Degree in Business, Communications, or any discipline', 'Sales training programs (SDR bootcamps)', 'Proven customer-facing service track record'],
    entry_pathways: ['Sales Development Representative (SDR)', 'Business Development Representative (BDR)', 'Account Executive Trainee', 'Inside Sales Specialist'],
    learning_areas: ['Multi-touch prospecting cadences', 'BANT & MEDDIC lead qualification', 'Handling pricing and timing objections', 'Running 15-minute qualification calls'],
    practical_tasks: ['Conduct a mock cold call handling 2 common brush-off objections in Practice Studio', 'Research and build a qualified lead list of 20 prospective companies with decision-maker emails', 'Draft a tailored 3-touch personalized outreach sequence'],
    portfolio_needs: ['Recorded mock discovery call in Practice Studio, sample outbound campaign sequence metrics'],
    work_environment: ['B2B software companies', 'Industrial distribution firms', 'Professional services agencies', 'Remote sales teams'],
    hands_on_level: 'Low',
    computer_use_level: 'Moderate',
    people_interaction_level: 'High',
    income_potential: 'High',
    learning_duration: '2-4 Months',
    related_careers: ['Digital Growth Marketer', 'Customer Success Specialist', 'Operations Coordinator']
  },

  // 14. AGRICULTURE & FOOD EXPANSION
  {
    id: 'car_agribusiness',
    career_name: 'Agribusiness & Food Processing Operations Specialist',
    category: 'Agriculture & Food',
    description: 'Manage post-harvest supply chains, cold storage preservation, food safety standard compliance (FSSAI/HACCP), and farmer-to-market distribution.',
    interest_areas: ['Agriculture', 'Food', 'Business', 'Operations', 'Practical Work'],
    work_styles: ['hands_on', 'practical', 'structured', 'team', 'outdoor'],
    common_skills: ['HACCP & Food Safety Compliance', 'Cold Chain & Post-Harvest Storage', 'Commodity Quality Grading', 'Inventory & Packing Logistics', 'Farmer Producer Organization (FPO) Liaison'],
    transferable_skills: ['Supply chain coordination', 'Quality assurance rigor', 'Vendor negotiation', 'Waste minimization mindset'],
    education_pathways: ['B.Sc in Agriculture / Food Technology / Agribusiness Management', 'Diploma in Food Processing & Quality Management', 'Practical farm cooperative management experience'],
    entry_pathways: ['Quality Control Executive', 'Packhouse Operations Supervisor', 'Agri Procurement Officer', 'Food Safety Associate'],
    learning_areas: ['Moisture testing and optical grading', 'Temperature loggers and cold storage management', 'Food labeling standards and trace audits', 'Direct-to-retail supply scheduling'],
    practical_tasks: ['Draft an HACCP hazard control flowchart for fresh produce packaging', 'Audit temperature logs across a 7-day cold storage cycle and identify deviations', 'Calculate post-harvest loss percentages and suggest moisture-barrier improvements'],
    portfolio_needs: ['Certified food safety inspection audit checklist, project report on reducing spoilage in perishable supply chains'],
    work_environment: ['Food processing plants', 'Agribusiness cooperatives', 'Perishable logistics hubs', 'Rural packhouses'],
    hands_on_level: 'High',
    computer_use_level: 'Moderate',
    people_interaction_level: 'High',
    income_potential: 'Good Growth',
    learning_duration: '4-8 Months',
    related_careers: ['Farm Operations Manager', 'Operations & Logistics Coordinator', 'Supply Chain Coordinator']
  },

  // 15. HOSPITALITY & TOURISM
  {
    id: 'car_hospitality',
    career_name: 'Hotel Operations & Guest Experience Lead',
    category: 'Hospitality & Tourism',
    description: 'Deliver exceptional guest services, coordinate front-of-house operations, supervise housekeeping standards, and resolve guest experiences with polish and warmth.',
    interest_areas: ['Hospitality', 'Helping people', 'Communication', 'Organization', 'Food'],
    work_styles: ['people_oriented', 'structured', 'fast_changing', 'hands_on', 'team'],
    common_skills: ['Property Management Systems (Opera/Cloud PMS)', 'Guest Concierge & Conflict De-escalation', 'Housekeeping Quality Audits', 'Revenue Management & Booking Channels', 'Food & Beverage Service Coordination'],
    transferable_skills: ['Grace under pressure', 'Exceptional interpersonal warmth', 'High cultural sensitivity', 'Multi-tasking across dynamic environments'],
    education_pathways: ['Degree / Diploma in Hotel Management (BHM / IHM)', 'Hospitality customer service certification', 'Front office operational experience'],
    entry_pathways: ['Front Desk Associate', 'Guest Relations Executive', 'Night Auditor', 'Assistant Floor Supervisor'],
    learning_areas: ['Check-in/check-out billing and currency handling', 'Managing difficult guest scenarios with service recovery', 'Room inspection 50-point checklists', 'OTA channel management'],
    practical_tasks: ['Simulate a high-stress guest complaint de-escalation in Practice Studio with empathetic service recovery', 'Perform a 20-point room turnover quality audit checklist', 'Analyze 30 days of hotel occupancy data to recommend weekend promotional pricing'],
    portfolio_needs: ['Guest satisfaction reviews and commendations, certified front office PMS assessment score'],
    work_environment: ['Boutique hotels & luxury resorts', 'Conference and event venues', 'Cruise ships', 'Hospitality chains'],
    hands_on_level: 'Moderate',
    computer_use_level: 'Moderate',
    people_interaction_level: 'High',
    income_potential: 'Good Growth',
    learning_duration: '3-6 Months',
    related_careers: ['Customer Success Specialist', 'Community Coordinator', 'Operations Coordinator']
  },

  // 16. LOGISTICS & SUPPLY CHAIN
  {
    id: 'car_warehouse_logistics',
    career_name: 'Warehouse Logistics & Supply Chain Coordinator',
    category: 'Logistics & Supply Chain',
    description: 'Oversee warehouse inventory accuracy, inbound freight staging, picking/packing workflows, and freight carrier dispatch to optimize on-time fulfillment.',
    interest_areas: ['Logistics', 'Organization', 'Computers', 'Practical Work', 'Problem Solving'],
    work_styles: ['structured', 'hands_on', 'computer_based', 'results_driven', 'team'],
    common_skills: ['Warehouse Management Systems (WMS)', 'Inventory Cycle Counting & Barcoding', 'Dispatch Routing & Carrier Coordination', 'OSHA / Warehouse Safety Rules', 'Freight Manifest Documentation'],
    transferable_skills: ['Systematic organization', 'Real-time bottleneck resolution', 'Data accuracy', 'Cross-team communication'],
    education_pathways: ['Diploma in Supply Chain & Logistics Management', 'APICS / ASCM foundational certificate', 'Practical warehouse supervisory experience'],
    entry_pathways: ['Warehouse Lead / Associate', 'Inventory Clerk', 'Logistics Dispatcher', 'Fulfillment Coordinator'],
    learning_areas: ['ABC inventory classification', 'Pick-path optimization to cut cycle times', 'Freight bill-of-lading (BOL) verification', 'Forklift and conveyor safety protocols'],
    practical_tasks: ['Execute a 100-item inventory cycle count and investigate variance discrepancies', 'Design an optimized warehouse aisle picking route reducing transit time by 15%', 'Draft standard operating procedures for handling hazardous inbound freight'],
    portfolio_needs: ['Inventory accuracy audit case study, WMS software certification or operational logbook'],
    work_environment: ['E-commerce fulfillment centers', 'Third-party logistics (3PL) warehouses', 'Manufacturing distribution plants', 'Freight terminals'],
    hands_on_level: 'High',
    computer_use_level: 'Moderate',
    people_interaction_level: 'Moderate',
    income_potential: 'Good Growth',
    learning_duration: '3-6 Months',
    related_careers: ['Operations & Logistics Coordinator', 'Agribusiness Operations Specialist', 'Appliance Repair Technician']
  }
];

export function seedCareerCatalog() {
  const insertStmt = db.prepare(`
    INSERT OR REPLACE INTO career_catalog (
      id, career_name, category, description, interest_areas, work_styles,
      common_skills, transferable_skills, education_pathways, entry_pathways,
      learning_areas, practical_tasks, portfolio_needs, work_environment,
      hands_on_level, computer_use_level, people_interaction_level,
      income_potential, learning_duration, related_careers
    ) VALUES (
      ?, ?, ?, ?, ?, ?,
      ?, ?, ?, ?,
      ?, ?, ?, ?,
      ?, ?, ?,
      ?, ?, ?
    )
  `);

  db.exec('BEGIN TRANSACTION;');
  try {
    for (const c of INITIAL_CAREER_CATALOG) {
      insertStmt.run(
        c.id,
        c.career_name,
        c.category,
        c.description,
        JSON.stringify(c.interest_areas),
        JSON.stringify(c.work_styles),
        JSON.stringify(c.common_skills),
        JSON.stringify(c.transferable_skills),
        JSON.stringify(c.education_pathways),
        JSON.stringify(c.entry_pathways),
        JSON.stringify(c.learning_areas),
        JSON.stringify(c.practical_tasks),
        JSON.stringify(c.portfolio_needs),
        JSON.stringify(c.work_environment),
        c.hands_on_level || 'Moderate',
        c.computer_use_level || 'Moderate',
        c.people_interaction_level || 'Moderate',
        c.income_potential || 'Good Growth',
        c.learning_duration || '6-12 Months',
        JSON.stringify(c.related_careers)
      );
    }
    db.exec('COMMIT;');
    console.log(`✅ Seeded ${INITIAL_CAREER_CATALOG.length} structured careers across 10+ diverse categories into career_catalog.`);
  } catch (err) {
    db.exec('ROLLBACK;');
    console.error('Failed to seed career catalog:', err);
  }
}
